# Generated by Django 4.2.7 on 2026-02-15 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.FloatField(help_text='Final weighted recommendation score (0-1)')),
                ('confidence_score', models.FloatField(help_text='Confidence in this recommendation (0-1)')),
                ('skill_match_score', models.FloatField(help_text='Skill matching component score (0-1)')),
                ('workload_score', models.FloatField(help_text='Workload analysis component score (0-1)')),
                ('historical_performance_score', models.FloatField(help_text='Historical performance component score (0-1)')),
                ('fairness_score', models.FloatField(help_text='Fairness & diversity component score (0-1)')),
                ('urgency_score', models.FloatField(help_text='Urgency alignment component score (0-1)')),
                ('rank_position', models.IntegerField(help_text='Position in ranked recommendations (1 = top recommendation)')),
                ('explanation', models.TextField(help_text='Human-readable explanation of recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_user', models.ForeignKey(help_text='User recommended for this task', on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendations', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Task for which recommendation was made', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='tasks.task')),
            ],
            options={
                'db_table': 'task_recommendations',
                'ordering': ['task', 'rank_position'],
                'indexes': [models.Index(fields=['task', 'rank_position'], name='task_recomm_task_id_baf6cc_idx'), models.Index(fields=['recommended_user', 'created_at'], name='task_recomm_recomme_25c0dc_idx')],
            },
        ),
    ]
