# Generated by Django 4.2.7 on 2026-07-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.FloatField(default=0.3)),
                ('workload', models.FloatField(default=0.25)),
                ('performance', models.FloatField(default=0.25)),
                ('fairness', models.FloatField(default=0.15)),
                ('urgency', models.FloatField(default=0.05)),
                ('version', models.IntegerField(default=1)),
                ('source', models.CharField(choices=[('default', 'Expert default'), ('learned', 'Learned from outcomes')], default='default', max_length=20)),
                ('n_samples', models.IntegerField(default=0, help_text='Number of outcomes used to train')),
                ('is_active', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendation_weights',
                'ordering': ['-created_at'],
            },
        ),
    ]
