# Generated by Django 4.2.7 on 2026-02-15 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkloadMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for these metrics')),
                ('active_tasks_count', models.IntegerField(default=0, help_text='Number of active assigned tasks', validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_tasks_count', models.IntegerField(default=0, help_text='Number of tasks completed on this date', validators=[django.core.validators.MinValueValidator(0)])),
                ('overdue_tasks_count', models.IntegerField(default=0, help_text='Number of overdue tasks', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_estimated_hours', models.DecimalField(decimal_places=2, default=0, help_text='Sum of estimated hours for active tasks', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('hours_logged', models.DecimalField(decimal_places=2, default=0, help_text='Actual hours logged on this date', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_quality_rating', models.FloatField(blank=True, help_text='Average quality rating for tasks completed', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('on_time_completion_rate', models.FloatField(blank=True, help_text='Percentage of tasks completed on time (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('workload_intensity', models.CharField(choices=[('underutilized', 'Underutilized'), ('optimal', 'Optimal'), ('heavy', 'Heavy'), ('overloaded', 'Overloaded')], default='optimal', help_text='Workload intensity classification', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_workload_metrics',
                'ordering': ['-date'],
            },
        ),
    ]
