# Generated by Django 4.2.7 on 2026-02-15 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkloadmetrics',
            name='user',
            field=models.ForeignKey(help_text='User these metrics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='workload_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userworkloadmetrics',
            index=models.Index(fields=['user', 'date'], name='user_worklo_user_id_a436ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='userworkloadmetrics',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_metrics'),
        ),
    ]
