# Generated by Django 4.2.7 on 2026-02-15 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('deadline_reminder_48h', 'Deadline Reminder (48h)'), ('deadline_reminder_24h', 'Deadline Reminder (24h)'), ('task_overdue', 'Task Overdue'), ('task_completed', 'Task Completed'), ('task_reassigned', 'Task Reassigned'), ('approval_request', 'Approval Request'), ('system_announcement', 'System Announcement')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', help_text='Notification priority level', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Has user read this notification?')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was marked as read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_task', models.ForeignKey(blank=True, help_text='Task this notification is about (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task')),
                ('user', models.ForeignKey(help_text='User receiving this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_5cf777_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
    ]
