# Generated by Django 4.2.7 on 2026-02-15 06:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed task description')),
                ('category', models.CharField(choices=[('development', 'Development'), ('testing', 'Testing'), ('design', 'Design'), ('documentation', 'Documentation'), ('research', 'Research'), ('review', 'Review'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', help_text='Task category', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Task priority level', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', help_text='Current task status', max_length=20)),
                ('required_skills', models.JSONField(blank=True, default=list, help_text="List of required skills (e.g., ['Python', 'Django'])")),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours spent (filled after completion)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('complexity_score', models.IntegerField(default=5, help_text='Complexity rating from 1 (easy) to 10 (very complex)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('deadline', models.DateTimeField(blank=True, help_text='Task deadline', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When work on the task started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment file paths')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(help_text='When work started')),
                ('completed_at', models.DateTimeField(help_text='When work was completed')),
                ('hours_taken', models.DecimalField(decimal_places=2, help_text='Actual hours spent', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('quality_rating', models.IntegerField(help_text='Quality rating 1-5 (assigned by manager)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('on_time', models.BooleanField(default=True, help_text='Was task completed before deadline?')),
                ('early_late_hours', models.DecimalField(decimal_places=2, default=0, help_text='Hours early (positive) or late (negative)', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about task completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(help_text='The completed task', on_delete=django.db.models.deletion.CASCADE, related_name='performance_log', to='tasks.task')),
                ('user', models.ForeignKey(help_text='User who completed the task', on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_performance_logs',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'completed_at'], name='task_perfor_user_id_7bd7ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('status_changed', 'Status Changed'), ('deleted', 'Deleted'), ('commented', 'Commented')], help_text='Type of action performed', max_length=20)),
                ('field_changed', models.CharField(blank=True, help_text='Field that was changed (for updates)', max_length=100)),
                ('old_value', models.JSONField(blank=True, help_text='Previous value', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New value', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Task that was modified', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tasks.task')),
                ('user', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['task', 'timestamp'], name='task_audit__task_id_f26e43_idx'), models.Index(fields=['user', 'timestamp'], name='task_audit__user_id_7ab9c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('ml_recommended', 'ML Recommended'), ('manual_override', 'Manual Override'), ('direct_assignment', 'Direct Assignment')], default='direct_assignment', help_text='How the assignment was made', max_length=30)),
                ('justification', models.TextField(blank=True, help_text='Explanation for assignment (required for overrides)')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_acknowledged', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current active assignment?')),
                ('reassignment_reason', models.TextField(blank=True, help_text='Reason for reassignment if is_active=False')),
                ('assigned_by', models.ForeignKey(help_text='User who made the assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='User to whom the task is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='The task being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task')),
            ],
            options={
                'db_table': 'task_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['task', 'is_active'], name='task_assign_task_id_6c0449_idx'), models.Index(fields=['assigned_to', 'is_active'], name='task_assign_assigne_3677c8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('task',), name='unique_active_assignment_per_task'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'deadline'], name='tasks_status_6d5acc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'status'], name='tasks_created_87eaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='tasks_categor_aecfa3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_priorit_a9efa1_idx'),
        ),
    ]
